#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

define('BASE_DIR', __DIR__);

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/');
$dotenv->load();

$application = new Application();

$application->add(new AHAbid\JiraItTest\Console\ReadCsvJiraIssuesAndSaveContentsCommand());

$application->run();
